HAI 1.2
OBTW FIND THE SUM OF ALL THE MULTIPLES OF 3 OR 5 BELOW 1000 (233168)
TLDR
I HAS A TOTL ITZ 0
IM IN YR LOOP UPPIN YR EYE TIL BOTH SAEM EYE AN 1000
   EITHER OF BOTH SAEM MOD OF EYE AN 3 AN 0 AN BOTH SAEM MOD OF EYE AN 5 AN 0
   O RLY?
   YA RLY
       TOTL R SUM OF TOTL AN EYE
   OIC
IM OUTTA YR LOOP
VISIBLE TOTL
KTHXBYE
